/*
2 - CRIAR UM SP PARA MOSTRAR O NOME E O TOTAL DE PEDIDOS REALIZADOS POR CLIENTES QUE
RESIDAM EM UMA DETERMINADA CIDADE PASSADA COMO PARAMETRO. 
UTILIZAR UM PARAMETRO DE SAIDA CONTENDO A MEDIA DOS PEDIDOS DESSES CLIENTES, 
DESDE QUE TAIS PEDIDOS TENHAM SIDO REALIZADOS ENTRE UMA DATA INICIAL E UMA DATA FINAL DE PEDIDO.*/

create procedure spu_media_vendas
@dataInicial date, @dataFinal date, @media float
as
begin
