USE [master]
GO

/****** Object:  Database [DW_VENDAS]    Script Date: 11/10/2016 20:40:11 ******/
CREATE DATABASE [DW_VENDAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_VENDAS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DW_VENDAS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DW_VENDAS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DW_VENDAS_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DW_VENDAS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_VENDAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DW_VENDAS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DW_VENDAS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DW_VENDAS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DW_VENDAS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DW_VENDAS] SET ARITHABORT OFF 
GO

ALTER DATABASE [DW_VENDAS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DW_VENDAS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DW_VENDAS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DW_VENDAS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DW_VENDAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DW_VENDAS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DW_VENDAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DW_VENDAS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DW_VENDAS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DW_VENDAS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DW_VENDAS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DW_VENDAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DW_VENDAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DW_VENDAS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DW_VENDAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DW_VENDAS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DW_VENDAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DW_VENDAS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DW_VENDAS] SET RECOVERY FULL 
GO

ALTER DATABASE [DW_VENDAS] SET  MULTI_USER 
GO

ALTER DATABASE [DW_VENDAS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DW_VENDAS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DW_VENDAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DW_VENDAS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DW_VENDAS] SET  READ_WRITE 
GO


